<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>opl</string>
   </array>
  <key>name</key>
  <string>opl</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.opl</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(PUBLIC|BLOCK)</string>
          <key>name</key>
          <string>keyword.control.opl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([_a-zA-Z0-9]+)</string>
          <key>name</key>
          <string>variable.other.opl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.line.number-sign.opl</string>
        </dict>
       </array>
    </dict>
    <key>expression</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(MAP|WHERE|AND|OR)</string>
          <key>name</key>
          <string>keyword.control.opl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\?|:|==|!=|&gt;=|&gt;|&lt;=|=|\+|-|\*|/|%|\.|,|;)</string>
          <key>name</key>
          <string>punctuation.opl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2}Z)?)</string>
          <key>name</key>
          <string>constant.character.opl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&quot;(?:\\&quot;|[^\x{0022}])*&quot;|&apos;(?:\\&apos;|[^\x{0027}])*&apos;)</string>
          <key>name</key>
          <string>string.quoted.opl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\d+(?:\.\d*)?)</string>
          <key>name</key>
          <string>constant.numeric.opl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(KEY|VALUE|ARG|NULL|NOW|TODAY|DAYS|HOURS|MINUTES|SECONDS|USERID|THREADID|PROJECTID|THIS)</string>
          <key>name</key>
          <string>constant.language.opl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([_a-zA-Z0-9]+)</string>
          <key>name</key>
          <string>variable.other.opl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expression__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>expression__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>expression__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>illegal</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\s]+)</string>
          <key>name</key>
          <string>invalid.illegal.opl</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#statement</string>
        </dict>
       </array>
    </dict>
    <key>statement</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(IF|ELSEIF|ELSE|WHILE|FOREACH|SWITCH|DEFAULT|RETURN)</string>
          <key>name</key>
          <string>keyword.control.opl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#statement__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.opl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>statement__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#statement</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
